{% load data_capture %}
<p>
  Hi there,
</p>
<p>
  We're emailing regarding the Region 10 CALC data upload <b>#{{ upload_source.id }}</b>, uploaded by <b>{{ upload_source.submitter.email }}</b> on <b>{{ upload_source.created_at|tz_timestamp }}</b>.
</p>
<p>
  Unfortunately, an <b>error occurred</b> while importing the data.
</p>
<p>
  Please visit <a href="{{ r10_upload_link }}">{{ r10_upload_link }}</a> to try uploading again.
</p>
<p>
  The traceback below may help the development team debug the problem.
</p>
<pre>
  {{ traceback }}
</pre>
<p>
  If you have any questions, reply to this email. We'll get back to you within two business days.
</p>
<p>
  Best,<br/>
  The CALC Team
</p>
